### ISSUE TITLE
Foreign Key Handling & Security

### ISSUE THREAD

**Issue by wesleyhstratusadv** [stratusadv/django-glue#22]
- [ ] Improved Handling and Security for selecting foreign keys. 

- foreign key implementation security and fuction
- Right now someone could change the ID of the foreign key and attach it to different objects. 
- When glueing both models and query sets you might need to provide a foreign key set in some capacity.
- Generic Relationships may be a big problem with overlaping foreign keys
- using parent to create children to avoid foreign key complexity
- Better handling of object creation on the javascript side with foriegn keys / parents

**Comment by nathanjstratusadv** [comment]
In the end we decided that this not something can be managed easily and does not fit the scope of django glue being easy and quick.
